name: incident_response_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  firebase_core: ^4.4.0
  image_picker: ^1.0.7
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  cloud_firestore: ^6.1.2
  firebase_storage: ^13.0.6
  firebase_auth: ^6.1.4
  http: ^1.2.0
  url_launcher: ^6.2.5

flutter:
  uses-material-design: true

  assets:
   - assets/images/app_icon.png
  
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
